name: Test and Deploy
on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
    run: echo 'hi there'
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout your repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          postgresql db: test_db
          postgresql user: Tests_Daily
          postgresql password: password!
      - name: install dependencies
        run: npm i
      - name: run tests
        run: PGDATABASE=test_db PGUSER=Tests_Daily PGPASSWORD=password! npm t
