name: Test and Deploy
on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "hi there"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout your repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          postgresql db: PGDATABASE=nc_games_test
          postgresql user: Tests_Daily
          postgresql password: password!
      - name: install dependencies
        run: npm i
      - name: run tests
        run: PGDATABASE=nc_games_test PGUSER=Tests_Daily PGPASSWORD=password! npm t

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone and checkout our repo
        uses: actions/checkout@v3
      - name: deploy to heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_email}}
